### ISSUE TITLE
Error running scalala.tensor.dense.DenseMatrixTest: Test FAILED

### ISSUE THREAD

**Issue by BAM-BAM-BAM** [scalala/Scalala#2]
[info] == scalala.tensor.dense.DenseMatrixTest ==
[info] Test Starting: Slicing
[error] Test Failed: Slicing
java.lang.ClassCastException: java.lang.Integer cannot be cast to scalala.tensor.Tensor
        at scalala.tensor.dense.DenseMatrixTest$$anonfun$1.apply(DenseMatrixTest.scala:33)
        at scalala.tensor.dense.DenseMatrixTest$$anonfun$1.apply(DenseMatrixTest.scala:33)
        at org.scalatest.FunSuite$$anon$2.apply(FunSuite.scala:1158)
        at org.scalatest.Suite$class.withFixture(Suite.scala:1509)
        at scalala.tensor.dense.DenseMatrixTest.withFixture(DenseMatrixTest.scala:31)
        at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1155)
        at scalala.tensor.dense.DenseMatrixTest.runTest(DenseMatrixTest.scala:31)
        at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1264)
        at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1255)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1255)
        at scalala.tensor.dense.DenseMatrixTest.runTests(DenseMatrixTest.scala:31)
        at org.scalatest.Suite$class.run(Suite.scala:1804)
        at scalala.tensor.dense.DenseMatrixTest.org$scalatest$FunSuite$$super$run(DenseMatrixTest.scala:31)
        at org.scalatest.FunSuite$class.run(FunSuite.scala:1304)
        at scalala.tensor.dense.DenseMatrixTest.run(DenseMatrixTest.scala:31)
        at org.scalatest.tools.ScalaTestFramework$ScalaTestRunner.run(ScalaTestFramework.scala:40)
        at sbt.TestRunner.run(TestFramework.scala:52)
        at sbt.TestRunner.runTest$1(TestFramework.scala:66)
        at sbt.TestRunner.run(TestFramework.scala:75)
        at sbt.TestFramework$$anonfun$9$$anonfun$apply$11.runTest$2(TestFramework.scala:192)
        at sbt.TestFramework$$anonfun$9$$anonfun$apply$11$$anonfun$apply$12.apply(TestFramework.scala:203)
        at sbt.TestFramework$$anonfun$9$$anonfun$apply$11$$anonfun$apply$12.apply(TestFramework.scala:203)
        at sbt.NamedTestTask.run(TestFramework.scala:91)
        at sbt.ScalaProject$$anonfun$sbt$ScalaProject$$toTask$1.apply(ScalaProject.scala:187)
        at sbt.ScalaProject$$anonfun$sbt$ScalaProject$$toTask$1.apply(ScalaProject.scala:187)
        at sbt.TaskManager$Task.invoke(TaskManager.scala:62)
        at sbt.impl.RunTask.doRun$1(RunTask.scala:77)
        at sbt.impl.RunTask.runTask(RunTask.scala:85)
        at sbt.impl.RunTask.sbt$impl$RunTask$$runIfNotRoot(RunTask.scala:60)
        at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
        at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
        at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
        at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
        at sbt.Control$.trapUnit(Control.scala:19)
        at sbt.Distributor$Run$Worker.run(ParallelRunner.scala:131)

==== environment ========
java -version
java version "1.6.0_23"
Java(TM) SE Runtime Environment (build 1.6.0_23-b05)
Java HotSpot(TM) 64-Bit Server VM (build 19.0-b09, mixed mode)

scala -version
Scala code runner version 2.8.1.final -- Copyright 2002-2010, LAMP/EPFL

I got the previous test failure when running "test" from sbt ... what other information do you need?

Thanks,
John

**Comment by scalala** [comment]
Hi John,

Thanks for filing this.  I'm running a very similar configuration but do not see this test failing on the current head (although admittedly, it wasn't failing for me on the previous head either).  Could you give it another try?

dramage

**Comment by dramage** [comment]
Assuming the problem is fixed ...

**Comment by BAM-BAM-BAM** [comment]
I don't know - I was running cygwin, gave up on it, and have installed Ubuntu and haven't gotten to the point where I need a linear algebra library again.
