### ISSUE TITLE
error in building scalala: "java.lang.Error: typeConstructor inapplicable for <none>"

### ISSUE THREAD

**Issue by yuexima123** [scalala/Scalala#61]
Hi,

I ran build.sbt when I am trying to build scalala, and after successfully compiling the 138 scala sources and 1 java source, there came three option:

```
                    [warn] Credentials file h:\Users\myx\.ivy2\.credentials does not exist
                    Multiple main classes detected, select one to run:
                    [1] scalala.ScalalaConsole
                    [2] scalala.operators.codegen.GeneratedRegistryEntries
                    [3] scalala.operators.codegen.GeneratedBinaryOpDefinitions
```

I selected 2 and 3 first, which returned success info. then i selected the first option, and there came this error:

```
                   [info] Running scalala.ScalalaConsole build
                   Loading h:\Users\myx\AppData\Local\Temp\scalala-startup-8352582697624731337.scala...
                   [error] (Thread-8) java.lang.Error: typeConstructor inapplicable for <none>
                   java.lang.Error: typeConstructor inapplicable for <none>
                           at scala.tools.nsc.symtab.SymbolTable.abort(SymbolTable.scala:34)
                           at scala.tools.nsc.symtab.Symbols$Symbol.typeConstructor(Symbols.scala:880)
                           at scala.tools.nsc.symtab.Definitions$definitions$.scala$tools$nsc$symtab$Definitions$definitions$$booltype(Definitions.scala:157)
                           at scala.tools.nsc.symtab.Definitions$definitions$.init(Definitions.scala:814)
                           at scala.tools.nsc.Global$Run.<init>(Global.scala:697)
                           at scala.tools.nsc.interpreter.IMain.scala$tools$nsc$interpreter$IMain$$_initialize(IMain.scala:114)
                           at scala.tools.nsc.interpreter.IMain$$anonfun$initialize$1.apply$mcZ$sp(IMain.scala:127)
                           at scala.tools.nsc.interpreter.IMain$$anonfun$initialize$2.apply(IMain.scala:126)
                           at scala.tools.nsc.interpreter.IMain$$anonfun$initialize$2.apply(IMain.scala:126)
                           at scala.concurrent.ThreadRunner$$anon$2$$anonfun$run$2.apply(ThreadRunner.scala:45)
                           at scala.concurrent.ThreadRunner.scala$concurrent$ThreadRunner$$tryCatch(ThreadRunner.scala:31)
                           at scala.concurrent.ThreadRunner$$anon$2.run(ThreadRunner.scala:45)
                           at java.lang.Thread.run(Thread.java:722) 
```

Does anyone have some idea on how to solve this? I really appreciate it!

Thanks,
Michael

**Comment by yuexima123** [comment]
i have figured out about this problem.. I should run the command "update compile test doc proguard " one by one and not with the "run" command.
